

```
This assignment involves working with matrices A, B and C using numpy.

Submit using mycourses dropbox. Save the file in ipynb format.

Your submission will be shared with all your classmates.

You are allowed to research code online or use LLM code
generators, but make sure you understand the code, otherwise
you will not be learning. It is a good idea to always look up
lectures notes and API documentation.

Make sure you present all results. It is a good idea to create a cell for each requirement results.

Requirements:

1. Double all the elements in A, store the result in A itself.
2. Calculate the matrix multiplication A times B, store it as D.
3. Consider C to be a column vector and add it to the right of A. Show the result without storing it. 
4. Transpose B and add it to the bottom of A (as extra rows).
5. Add B to itself, store the result as E.
6. Add C to itself as a new row (considering C now to be a row vector), and store the result in F. The results should be a 2x3 matrix.
7. Calculate the element-wise multiplication between F and B.
8. Calculate the element-wise multiplication between C and B (this will result in using numpy broadcasting).
9. Change the shape of C to be a 3x1 array, store it as G. Change the shape of C to be a 1x3 array, store it as H.
10. Calculate the element-wise multiplication between G and H (note that numpy will broadcast now in two dimensions).
```



In [77]:
# create matrices
import numpy as np
a = np.array([[2,3],[2,3],[2,3]])
b = np.array([[3,3,3],[2,2,2]])
c = np.array([4,4,4])

In [78]:
# 1. double all elements in a
a = np.multiply(a, 2)
a

array([[4, 6],
       [4, 6],
       [4, 6]])

In [79]:
# 2. calculate d = a * b
d = a @ b # or np.matmul(a, b)
d

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]])

In [80]:
# 3. augment right side of a with c

# use reshape to interpret c as column vector
np.concatenate((a, c.reshape(-1, 1)), axis=1)

array([[4, 6, 4],
       [4, 6, 4],
       [4, 6, 4]])

In [81]:
# 4. transpose B, add to bottom of A
b_t = b.T # or np.transpose(b)

np.concatenate((a, b_t))

array([[4, 6],
       [4, 6],
       [4, 6],
       [3, 2],
       [3, 2],
       [3, 2]])

In [82]:
# 5. Add b to itself
e = b + b
e

array([[6, 6, 6],
       [4, 4, 4]])

In [83]:
# 6. add c to itself as new row
f = np.vstack((c, c))
f

array([[4, 4, 4],
       [4, 4, 4]])

In [84]:
# 7. element-wise f * b
f * b

array([[12, 12, 12],
       [ 8,  8,  8]])

In [85]:
# 8. element-wise c * b (broadcasting wizardry)
c * b

array([[12, 12, 12],
       [ 8,  8,  8]])

In [86]:
# 9. make g = c 3x1 array
g = np.reshape(c, (3, 1))
print(g)

h = np.reshape(c, (1, 3))
print(h)

[[4]
 [4]
 [4]]
[[4 4 4]]


In [87]:
# 10. Calculate the element-wise multiplication between G and H (note that numpy will broadcast now in two dimensions).
g * h

array([[16, 16, 16],
       [16, 16, 16],
       [16, 16, 16]])